# Generated by Django 5.2.17 on 2026-09-17 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'OK'), ('partial', 'Finished with errors'), ('failed', 'Failed')], default='running', max_length=10)),
                ('trigger', models.CharField(choices=[('cli', 'Command line / cron'), ('ui', 'Settings page')], default='cli', max_length=10)),
                ('sources', models.CharField(blank=True, max_length=200)),
                ('posts_seen', models.IntegerField(default=0)),
                ('posts_new', models.IntegerField(default=0)),
                ('comments_fetched', models.IntegerField(default=0)),
                ('images_cached', models.IntegerField(default=0)),
                ('recommendations_created', models.IntegerField(default=0)),
                ('requests_made', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
