# Generated by Django 5.2.17 on 2026-09-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='blocked',
            field=models.BooleanField(default=False, help_text='Reddit refused us (rate limit / interstitial) during this run'),
        ),
    ]
