# Generated by Django 5.2.17 on 2026-09-17 08:20

import integrations.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('radarr', 'Radarr'), ('lidarr', 'Lidarr'), ('jellyfin', 'Jellyfin'), ('navidrome', 'Navidrome')], max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('url', models.URLField(blank=True, help_text='Base URL, e.g. http://192.168.1.110:7878')),
                ('api_key', integrations.fields.EncryptedTextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', integrations.fields.EncryptedTextField(blank=True)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_message', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service'],
            },
        ),
    ]
