# Generated by Django 5.2.17 on 2026-09-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfig',
            name='service',
            field=models.CharField(choices=[('radarr', 'Radarr'), ('lidarr', 'Lidarr'), ('jellyfin', 'Jellyfin'), ('navidrome', 'Navidrome'), ('slskd', 'slskd')], max_length=20, unique=True),
        ),
    ]
