# Generated by Django 5.2.17 on 2026-09-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_serviceconfig_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfig',
            name='service',
            field=models.CharField(choices=[('radarr', 'Radarr'), ('lidarr', 'Lidarr'), ('jellyfin', 'Jellyfin'), ('navidrome', 'Navidrome'), ('slskd', 'slskd'), ('tmdb', 'TheMovieDB'), ('lastfm', 'Last.fm')], max_length=20, unique=True),
        ),
    ]
