# Generated by Django 5.2.17 on 2026-09-17 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=80)),
                ('permalink', models.CharField(help_text='Path on reddit.com', max_length=500)),
                ('url', models.URLField(blank=True, help_text='Link target of the post', max_length=1000)),
                ('selftext', models.TextField(blank=True)),
                ('flair', models.CharField(blank=True, max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('upvote_ratio', models.FloatField(blank=True, null=True)),
                ('num_comments', models.IntegerField(default=0)),
                ('created_utc', models.DateTimeField(db_index=True)),
                ('is_gallery', models.BooleanField(default=False)),
                ('is_video', models.BooleanField(default=False)),
                ('nsfw', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('comments', models.JSONField(blank=True, default=list)),
                ('comments_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('comments_fetched_count', models.IntegerField(default=0, help_text='num_comments at the time comments were last fetched')),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hidden', models.BooleanField(default=False, help_text='Hide from the tile grid')),
                ('starred', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_utc'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('movies', 'Movies'), ('music', 'Music')], max_length=10)),
                ('subreddit', models.CharField(help_text='Without the r/ prefix', max_length=60, unique=True)),
                ('listing', models.CharField(choices=[('hot', 'Hot'), ('new', 'New'), ('top', 'Top'), ('rising', 'Rising')], default='hot', max_length=10)),
                ('time_filter', models.CharField(choices=[('day', 'Past day'), ('week', 'Past week'), ('month', 'Past month'), ('year', 'Past year'), ('all', 'All time')], default='month', help_text="Only used when listing is 'top'", max_length=10)),
                ('fetch_limit', models.PositiveSmallIntegerField(default=50, help_text='How many posts to pull from the listing each sync (max 100)')),
                ('enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['kind', 'subreddit'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(blank=True, max_length=20)),
                ('comment_author', models.CharField(blank=True, max_length=80)),
                ('comment_score', models.IntegerField(default=0)),
                ('comment_depth', models.PositiveSmallIntegerField(default=0)),
                ('comment_permalink', models.CharField(blank=True, max_length=500)),
                ('raw_text', models.TextField(blank=True, help_text='Comment body the candidate came from')),
                ('snippet', models.CharField(blank=True, help_text='The exact fragment matched', max_length=300)),
                ('parsed_title', models.CharField(blank=True, help_text='Blank = artist-only recommendation', max_length=300)),
                ('parsed_artist', models.CharField(blank=True, max_length=200)),
                ('parsed_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parsed_url', models.URLField(blank=True, max_length=1000)),
                ('method', models.CharField(choices=[('link', 'Link in comment'), ('artist_title', 'Artist - Title pattern'), ('title_by_artist', 'Title by Artist pattern'), ('title_year', 'Title (Year) pattern'), ('quoted', 'Quoted / italic title'), ('list_item', 'List item'), ('short_comment', 'Whole short comment'), ('titlecase', 'Title-case run in sentence'), ('manual', 'Added manually')], max_length=20)),
                ('confidence', models.FloatField(default=0.5)),
                ('mention_count', models.PositiveSmallIntegerField(default=1)),
                ('included', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('edited', models.BooleanField(default=False, help_text='Set once a human touches it; re-parsing then leaves it alone')),
                ('integration_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='vibes.post')),
            ],
            options={
                'ordering': ['post', 'order', '-confidence'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='vibes.source'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source_url', models.URLField(max_length=1000)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('file', models.ImageField(blank=True, upload_to='posts/')),
                ('thumb', models.ImageField(blank=True, upload_to='thumbs/')),
                ('cached_at', models.DateTimeField(blank=True, null=True)),
                ('cache_failed', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vibes.post')),
            ],
            options={
                'ordering': ['post', 'order'],
                'unique_together': {('post', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['source', '-created_utc'], name='vibes_post_source__f5cf0d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-score'], name='vibes_post_score_476294_idx'),
        ),
    ]
