# Generated by Django 5.2.17 on 2026-09-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('norm', models.CharField(max_length=200, unique=True)),
                ('source', models.CharField(choices=[('lidarr', 'Lidarr library'), ('musicbrainz', 'MusicBrainz'), ('manual', 'Manual')], default='musicbrainz', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['norm'],
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
